#!/bin/bash

PIF_VALIDATOR="/Users/alex/confluence/tests/jpif-validator.json"

if ! [ -f "$PIF_VALIDATOR" ] ; then
    echo "Could not find jpif-validator." >&2
    exit 1
fi

java -jar "$PIF_VALIDATOR" ${1?Usage: ${0##*/} file-to-check.pif}

exit 1